import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "For Recruiters & Employers",
  description:
    "Connect with candidates and explore recruiting opportunities with Horizon Jobs.",
  alternates: {
    canonical: "https://horizonjobs.online/recruiters",
  },
};import Link from "next/link";import {ArrowRight,BriefcaseBusiness,Building2,FileCheck2,UsersRound} from "lucide-react";
export default function RecruitersPage(){return <main className="horizon-page"><section className="relative overflow-hidden bg-[#071a35] py-20 text-white"><div className="horizon-container relative"><p className="horizon-eyebrow">For employers</p><h1 className="mt-4 max-w-3xl text-5xl font-black leading-[1.04] md:text-6xl">Hire better.<br/><span className="text-[#e4ad2f]">Reach the right people.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/60">Publish jobs, organize your company presence and manage your hiring workflow through Horizon Jobs.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/recruiter/signup" className="horizon-button horizon-button-gold">Create recruiter account <ArrowRight size={16}/></Link><Link href="/recruiter/login" className="horizon-button border border-white/15 bg-white/5 text-white">Recruiter sign in</Link></div></div></section><section className="horizon-container horizon-section"><div className="max-w-2xl"><p className="horizon-eyebrow">Employer tools</p><h2 className="mt-2 text-3xl font-black">Everything starts with a clean workflow.</h2></div><div className="mt-8 grid gap-5 md:grid-cols-3"><Feature icon={<BriefcaseBusiness/>} title="Post jobs" text="Create structured listings with location, category, work mode and salary information."/><Feature icon={<UsersRound/>} title="Manage candidates" text="Keep applications organized around the jobs your company owns."/><Feature icon={<Building2/>} title="Company presence" text="Maintain a clear employer identity and company information."/></div></section><section className="bg-white py-14"><div className="horizon-container grid gap-8 md:grid-cols-2 md:items-center"><div><p className="horizon-eyebrow">Ready to hire?</p><h2 className="mt-2 text-3xl font-black text-[#071a35]">Create your employer workspace.</h2><p className="mt-3 text-sm leading-7 text-slate-500">New job listings enter review status before they are published.</p></div><div className="grid gap-3 sm:grid-cols-2"><Step n="01" text="Create recruiter account"/><Step n="02" text="Set up company"/><Step n="03" text="Post your job"/><Step n="04" text="Review applications"/></div></div></section></main>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="horizon-card horizon-card-hover p-7"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#071a35] text-[#e4ad2f]">{icon}</span><h3 className="mt-5 text-lg font-black text-[#071a35]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}function Step({n,text}:{n:string;text:string}){return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><span className="text-[10px] font-black text-[#b88410]">{n}</span><p className="mt-1 text-sm font-black text-[#071a35]">{text}</p></div>}


