import Link from "next/link";
import { BriefcaseBusiness, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { getPublishedJobs, type Job } from "@/lib/jobs";

function one<T>(value:T|T[]|null|undefined):T|null { return Array.isArray(value) ? value[0] ?? null : value ?? null; }
function money(job:Job){ if(job.salary_min==null&&job.salary_max==null)return "Salary not specified"; const c=job.currency?`${job.currency} `:""; if(job.salary_min!=null&&job.salary_max!=null)return `${c}${job.salary_min.toLocaleString()} – ${job.salary_max.toLocaleString()}`; return job.salary_min!=null?`${c}${job.salary_min.toLocaleString()}+`:`Up to ${c}${job.salary_max!.toLocaleString()}`; }

export default async function JobsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const p=await searchParams; const search=typeof p.search==="string"?p.search:""; const location=typeof p.location==="string"?p.location:""; let jobs:Job[]=[]; let failed=false;
 try{jobs=await getPublishedJobs(search,location,50)}catch{failed=true}
 return <main className="horizon-page"><section className="bg-[#071a35] py-12 text-white"><div className="horizon-container"><p className="horizon-eyebrow">Horizon Jobs marketplace</p><h1 className="mt-3 text-4xl font-black md:text-5xl">Find your next opportunity</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Search published opportunities from the Horizon Jobs database.</p><form className="mt-7 grid gap-2 rounded-2xl bg-white p-2 shadow-xl md:grid-cols-[1fr_1fr_auto]"><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-4"><Search size={17} className="text-slate-400"/><input name="search" defaultValue={search} className="h-12 min-w-0 flex-1 text-sm text-slate-900 outline-none" placeholder="Job title, company or keyword"/></label><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-4"><MapPin size={17} className="text-slate-400"/><input name="location" defaultValue={location} className="h-12 min-w-0 flex-1 text-sm text-slate-900 outline-none" placeholder="City or country"/></label><button className="h-12 rounded-xl bg-[#e4ad2f] px-7 text-sm font-black text-[#071a35]">Search jobs</button></form></div></section>
 <section className="horizon-container py-10"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#b88410]">Published roles</p><h2 className="mt-2 text-2xl font-black text-[#071a35]">{search||location?"Search results":"Latest jobs"}</h2></div><span className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-500"><SlidersHorizontal size={14}/>{jobs.length} results</span></div>
 {failed?<div className="horizon-card border-red-200 bg-red-50 p-8"><h3 className="font-black text-red-900">Jobs could not be loaded</h3><p className="mt-2 text-sm text-red-700">The database connection is unavailable. Check the Supabase server configuration; no fake jobs are shown.</p></div>:jobs.length===0?<div className="horizon-card p-12 text-center"><BriefcaseBusiness className="mx-auto text-slate-300" size={40}/><h3 className="mt-4 text-lg font-black">No published jobs found</h3><p className="mt-2 text-sm text-slate-500">Try a different search or check back when employers publish new roles.</p></div>:<div className="grid gap-5 lg:grid-cols-2">{jobs.map(job=><JobCard key={job.id} job={job}/>)}</div>}</section></main>
}
function JobCard({job}:{job:Job}){const c=one(job.companies),cat=one(job.categories);return <Link href={`/jobs/${job.slug}`} className="horizon-card horizon-card-hover block p-6"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#071a35] font-black text-[#e4ad2f]">{c?.name?.charAt(0)||"J"}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-[#071a35]">{job.title}</h3><p className="mt-1 text-sm text-slate-500">{c?.name||"Employer"}</p></div><span className="rounded-lg bg-slate-50 px-2 py-1 text-[10px] font-black uppercase text-slate-500">{job.status}</span></div><div className="mt-4 flex flex-wrap gap-2 text-xs">{cat?.name&&<Badge>{cat.name}</Badge>}{job.city&&<Badge>{job.city}</Badge>}{job.work_mode&&<Badge>{job.work_mode}</Badge>}{job.employment_type&&<Badge>{job.employment_type}</Badge>}</div><div className="mt-5 border-t border-slate-100 pt-4 text-sm font-black text-[#071a35]">{money(job)}</div></div></div></Link>}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 font-bold text-slate-600">{children}</span>}
